-- DropForeignKey
ALTER TABLE "Book" DROP CONSTRAINT IF EXISTS "Book_author_id_fkey";

-- DropForeignKey
ALTER TABLE "Review" DROP CONSTRAINT IF EXISTS "Review_book_id_fkey";

-- DropForeignKey
ALTER TABLE "Review" DROP CONSTRAINT IF EXISTS "Review_user_id_fkey";

-- AlterTable
ALTER TABLE "Book" DROP COLUMN IF EXISTS "author_id";
ALTER TABLE "Book" ADD COLUMN IF NOT EXISTS "authorId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Book" ALTER COLUMN "authorId" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Review" DROP COLUMN IF EXISTS "book_id";
ALTER TABLE "Review" DROP COLUMN IF EXISTS "user_id";
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "bookId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ADD COLUMN IF NOT EXISTS "userId" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Review" ALTER COLUMN "bookId" DROP DEFAULT;
ALTER TABLE "Review" ALTER COLUMN "userId" DROP DEFAULT;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "User_username_key" ON "User"("username");

-- AddForeignKey
ALTER TABLE "Book" ADD CONSTRAINT "Book_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "Author"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Review" ADD CONSTRAINT "Review_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Review" ADD CONSTRAINT "Review_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;